import { useEffect, useState } from 'react'
import { alerts, actions, inspections, mines } from '../data/dashboardData'
import { useAuth } from '../context/AuthContext'
import { roleDetails } from '../data/mockUsers'
import { SectionCard, StatusBadge } from '../components/ui'
import { workflowService, type DashboardSummary } from '../services/workflow'

export function DashboardPage() {
  const { user } = useAuth(); const [summary, setSummary] = useState<DashboardSummary | null>(null); const [error, setError] = useState('')
  useEffect(() => { workflowService.dashboardSummary().then(setSummary).catch(() => setError('Unable to load live dashboard metrics.')).finally(() => undefined) }, [])
  if (!user) return null
  const greeting = roleDetails[user.role]?.greeting ?? 'Operational overview'
  const metrics = summary ? [{ label: 'Total mines', value: String(summary.totalMines), change: 'Across monitored operations', tone: 'blue', icon: 'M' }, { label: 'Compliance', value: summary.compliancePercent === null ? '—' : `${summary.compliancePercent}%`, change: 'Live backend summary', tone: 'green', icon: 'OK' }, { label: 'Open violations', value: String(summary.openViolations), change: 'Current unresolved records', tone: 'amber', icon: '!' }, { label: 'Critical violations', value: String(summary.criticalViolations), change: 'Immediate management attention', tone: 'red', icon: '!' }, { label: 'Overdue actions', value: String(summary.overdueActions), change: 'Deadline-based calculation', tone: 'red', icon: '>' }, { label: 'Risk score', value: summary.riskScore === null ? '—' : String(summary.riskScore), change: 'Not configured by product rules', tone: 'amber', icon: 'R' }] : []
  return <div className="space-y-6"><div className="flex sm:flex-row flex-col justify-between sm:items-end gap-3"><div><p className="font-medium text-minsos-600 text-sm">{greeting}</p><h2 className="mt-1 font-bold text-slate-900 text-2xl tracking-tight">Good morning, {user.name.split(' ')[0]}</h2><p className="mt-1 text-slate-500 text-sm">Priority signals across your monitored operations.</p></div><p className="text-slate-500 text-sm">{summary ? `Updated ${new Date(summary.generatedAt).toLocaleString()}` : 'Loading live metrics...'}</p></div>{error && <p className="bg-red-50 px-4 py-3 rounded-lg text-red-700 text-sm">{error}</p>}<div className="gap-4 grid sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <article key={metric.label} className="bg-white p-5 border border-slate-200 rounded-xl"><div className="flex justify-between items-start"><p className="font-medium text-slate-600 text-sm">{metric.label}</p><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${metric.tone === 'red' ? 'bg-red-50 text-red-600' : metric.tone === 'amber' ? 'bg-amber-50 text-amber-600' : metric.tone === 'green' ? 'bg-emerald-50 text-emerald-600' : 'bg-minsos-50 text-minsos-600'}`}>{metric.icon}</span></div><p className="mt-4 font-bold text-slate-900 text-3xl tracking-tight">{metric.value}</p><p className="mt-1.5 text-slate-500 text-xs">{metric.change}</p></article>)}{!summary && !error && <p className="text-slate-500 text-sm">Loading dashboard metrics...</p>}</div>
  <div className="gap-6 grid xl:grid-cols-[1.2fr_.8fr]"><SectionCard title="Mine risk ranking" subtitle="Demo records until mine analytics are connected"><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-sm text-left"><thead className="bg-slate-50 text-slate-500 text-xs uppercase tracking-wide"><tr><th className="px-5 py-3 font-semibold">Mine</th><th className="px-4 py-3 font-semibold">Compliance</th><th className="px-4 py-3 font-semibold">Risk</th><th className="px-5 py-3 font-semibold text-right">Open items</th></tr></thead><tbody className="divide-y divide-slate-100">{mines.map((mine) => <tr key={mine.name} className="hover:bg-slate-50/70"><td className="px-5 py-3.5"><p className="font-semibold text-slate-800">{mine.name}</p><p className="text-slate-500 text-xs">{mine.location}</p></td><td className="px-4 py-3.5"><span className="font-medium text-slate-700">{mine.compliance}%</span></td><td className="px-4 py-3.5"><StatusBadge value={`${mine.risk} risk`} /></td><td className="px-5 py-3.5 font-semibold text-slate-700 text-right">{mine.openItems}</td></tr>)}</tbody></table></div></SectionCard><SectionCard title="Recent alerts" subtitle="Demo records until alert APIs are connected"><div className="divide-y divide-slate-100">{alerts.map((alert) => <div key={alert.id} className="flex gap-3 px-5 py-4"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${alert.severity === 'High' ? 'bg-red-500' : alert.severity === 'Medium' ? 'bg-amber-500' : 'bg-minsos-500'}`} /><div><p className="font-semibold text-slate-800">{alert.title}</p><p className="mt-1 text-slate-500 text-sm">{alert.detail}</p></div></div>)}</div></SectionCard></div>
  <div className="gap-6 grid xl:grid-cols-2"><SectionCard title="Recent inspections" subtitle="Demo records until inspection summary APIs are connected"><div className="divide-y divide-slate-100">{inspections.map((inspection) => <div key={inspection.id} className="flex justify-between items-center gap-4 px-5 py-3.5"><div><p className="font-semibold text-slate-800 text-sm">{inspection.mine} <span className="font-normal text-slate-400">· {inspection.id}</span></p><p className="mt-0.5 text-slate-500 text-xs">{inspection.type} · {inspection.date}</p></div><StatusBadge value={inspection.result} /></div>)}</div></SectionCard><SectionCard title="Open corrective actions" subtitle="Demo records until action summary APIs are connected"><div className="divide-y divide-slate-100">{actions.map((action) => <div key={action.id} className="flex justify-between items-center gap-4 px-5 py-3.5"><div className="min-w-0"><p className="font-semibold text-slate-800 text-sm truncate">{action.action}</p><p className="mt-0.5 text-slate-500 text-xs">{action.mine} · {action.owner} · due {action.due}</p></div><StatusBadge value={action.status} /></div>)}</div></SectionCard></div></div>
}