import { alerts, actions, inspections, metrics, mines } from '../data/dashboardData'
import { useAuth } from '../context/AuthContext'
import { roleDetails } from '../data/mockUsers'
import { SectionCard, StatusBadge } from '../components/ui'

export function DashboardPage() {
  const { user } = useAuth(); if (!user) return null
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-minsos-600">{roleDetails[user.role].greeting}</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Good morning, {user.name.split(' ')[0]}</h2><p className="mt-1 text-sm text-slate-500">Priority signals across your monitored operations.</p></div><p className="text-sm text-slate-500">Last updated <time dateTime="2026-09-05T09:30:00+05:30">05 Sep 2026, 09:30 IST</time></p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <article key={metric.label} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><p className="text-sm font-medium text-slate-600">{metric.label}</p><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${metric.tone === 'red' ? 'bg-red-50 text-red-600' : metric.tone === 'amber' ? 'bg-amber-50 text-amber-600' : metric.tone === 'green' ? 'bg-emerald-50 text-emerald-600' : 'bg-minsos-50 text-minsos-600'}`}>{metric.icon}</span></div><p className="mt-4 text-3xl font-bold tracking-tight text-slate-900">{metric.value}</p><p className="mt-1.5 text-xs text-slate-500">{metric.change}</p></article>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><SectionCard title="Mine risk ranking" subtitle="Ordered by current compliance attention" action={<button className="text-sm font-semibold text-minsos-600 hover:text-minsos-800">View all mines</button>}><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-semibold">Mine</th><th className="px-4 py-3 font-semibold">Compliance</th><th className="px-4 py-3 font-semibold">Risk</th><th className="px-5 py-3 text-right font-semibold">Open items</th></tr></thead><tbody className="divide-y divide-slate-100">{mines.map((mine) => <tr key={mine.name} className="hover:bg-slate-50/70"><td className="px-5 py-3.5"><p className="font-semibold text-slate-800">{mine.name}</p><p className="text-xs text-slate-500">{mine.location}</p></td><td className="px-4 py-3.5"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded bg-slate-100"><div className={`h-full rounded ${mine.compliance < 80 ? 'bg-red-500' : mine.compliance < 90 ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${mine.compliance}%` }} /></div><span className="font-medium text-slate-700">{mine.compliance}%</span></div></td><td className="px-4 py-3.5"><StatusBadge value={`${mine.risk} risk`} /></td><td className="px-5 py-3.5 text-right font-semibold text-slate-700">{mine.openItems}</td></tr>)}</tbody></table></div></SectionCard>
  <SectionCard title="Recent alerts" subtitle="Items requiring visibility"><div className="divide-y divide-slate-100">{alerts.map((alert) => <div key={alert.id} className="flex gap-3 px-5 py-4"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${alert.severity === 'High' ? 'bg-red-500' : alert.severity === 'Medium' ? 'bg-amber-500' : 'bg-minsos-500'}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-x-2"><p className="font-semibold text-slate-800">{alert.title}</p><time className="text-xs text-slate-400">{alert.time}</time></div><p className="mt-1 text-sm text-slate-500">{alert.detail}</p></div></div>)}</div></SectionCard></div>
  <div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Recent inspections" subtitle="Latest field and statutory records" action={<button className="text-sm font-semibold text-minsos-600">Inspection register</button>}><div className="divide-y divide-slate-100">{inspections.map((inspection) => <div key={inspection.id} className="flex items-center justify-between gap-4 px-5 py-3.5"><div><p className="font-semibold text-sm text-slate-800">{inspection.mine} <span className="font-normal text-slate-400">· {inspection.id}</span></p><p className="mt-0.5 text-xs text-slate-500">{inspection.type} · {inspection.date}</p></div><StatusBadge value={inspection.result} /></div>)}</div></SectionCard><SectionCard title="Open corrective actions" subtitle="Ownership and due-date monitoring" action={<button className="text-sm font-semibold text-minsos-600">Action tracker</button>}><div className="divide-y divide-slate-100">{actions.map((action) => <div key={action.id} className="flex items-center justify-between gap-4 px-5 py-3.5"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{action.action}</p><p className="mt-0.5 text-xs text-slate-500">{action.mine} · {action.owner} · due {action.due}</p></div><StatusBadge value={action.status} /></div>)}</div></SectionCard></div><p className="text-xs text-slate-400">All dashboard values are clearly labelled demo data and will be replaced through the API service layer after backend integration.</p></div>
}
