import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { SectionCard, StatusBadge } from '../components/ui'
import { workflowService, type InspectionDetail, type WorkflowLookup } from '../services/workflow'
import type { WorkflowInspection } from '../types'
import { useAuth } from '../context/AuthContext'

export function InspectionListPage() {
  const [items, setItems] = useState<WorkflowInspection[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false)
  const load = () => { setLoading(true); workflowService.inspections().then((result) => setItems(result.data)).catch(() => setError('Unable to load inspections from the backend.')).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [])
  return <div className="space-y-6"><div className="flex justify-between items-end gap-3"><Heading title="Inspection register" description="Field and statutory inspections, including their follow-up work." /><button onClick={() => setShowForm((value) => !value)} className="bg-minsos-600 px-4 py-2.5 rounded-lg font-semibold text-white text-sm">{showForm ? 'Close' : 'New inspection'}</button></div>{showForm && <InspectionForm onCreated={() => { setShowForm(false); load() }} onError={setError} />}<SectionCard title="All inspections" subtitle="Select an inspection to view evidence and linked workflow records.">{loading && <State text="Loading inspections..." />}{error && <State text={error} error />}{!loading && !error && <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm text-left"><thead className="bg-slate-50 text-slate-500 text-xs uppercase tracking-wide"><tr><th className="px-5 py-3">Inspection</th><th className="px-4 py-3">Mine</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Inspector</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Workflow</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="px-5 py-4"><Link to={`../inspections/${item.id}`} className="font-semibold text-minsos-600">{item.id}</Link><p className="text-slate-500 text-xs">{item.completedOn ?? `Scheduled ${item.scheduledFor}`}</p></td><td className="px-4 py-4">{item.mine}<p className="text-slate-500 text-xs">{item.mineCode}</p></td><td className="px-4 py-4">{item.type}</td><td className="px-4 py-4">{item.inspector}</td><td className="px-4 py-4"><StatusBadge value={item.status} /></td><td className="px-5 py-4 text-slate-500 text-xs text-right">{item.violationCount} violations · {item.actionCount} actions</td></tr>)}</tbody></table>{!items.length && <State text="No inspections have been recorded yet." />}</div>}</SectionCard></div>
}

function InspectionForm({ onCreated, onError }: { onCreated: () => void; onError: (message: string) => void }) { const { user } = useAuth(); const [mines, setMines] = useState<WorkflowLookup[]>([]); const [users, setUsers] = useState<WorkflowLookup[]>([]); const [mineId, setMineId] = useState(''); const [inspectorId, setInspectorId] = useState(user?.id ?? ''); const [type, setType] = useState('Statutory safety'); const [scheduledFor, setScheduledFor] = useState(''); const [location, setLocation] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { workflowService.mines().then(setMines).catch(() => onError('Unable to load mines.')); workflowService.users('inspector').then(setUsers).catch(() => { if (user?.id) setUsers([{ id: user.id, name: user.name, label: `${user.name} (current user)` }]) }) }, [onError, user])
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await workflowService.createInspection({ mineId, inspectorId, type, scheduledFor, location }); onCreated() } catch { onError('Unable to create inspection. Check the selected mine, inspector, date, and permissions.') } finally { setBusy(false) } }
  return <WorkflowForm onSubmit={submit} label={busy ? 'Saving...' : 'Create inspection'}><Select label="Mine" value={mineId} onChange={setMineId} options={mines} required /><Select label="Inspector" value={inspectorId} onChange={setInspectorId} options={users} required /><Input label="Inspection type" value={type} onChange={setType} required /><Input label="Scheduled date" type="date" value={scheduledFor} onChange={setScheduledFor} required /><Input label="Location" value={location} onChange={setLocation} /></WorkflowForm>
}

export function InspectionDetailPage() { const { id } = useParams(); const [item, setItem] = useState<InspectionDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { if (id) workflowService.inspection(id).then(setItem).catch(() => setError('Unable to load this inspection.')).finally(() => setLoading(false)) }, [id]); if (loading) return <State text="Loading inspection..." />; if (error || !item) return <State text={error || 'Inspection not found'} error />; return <div className="space-y-6"><Link to="../inspections" className="font-semibold text-minsos-600 text-sm">← Inspection register</Link><div><p className="font-semibold text-minsos-600 text-sm">{item.mine} · {item.mineCode}</p><h2 className="mt-1 font-bold text-slate-900 text-2xl">{item.id} — {item.type}</h2><p className="mt-1 text-slate-500 text-sm">Completed {item.completedOn ?? '—'} by {item.inspector}</p></div><div className="gap-4 grid sm:grid-cols-3"><Info label="Location" value={item.location || 'Not recorded'} /><Info label="GPS" value={`${item.latitude.toFixed(4)}, ${item.longitude.toFixed(4)}`} /><Info label="Evidence" value={`${item.photoCount} attached`} /></div><SectionCard title="Inspector observations" subtitle="Recorded during the field visit"><p className="px-5 py-5 text-slate-700 text-sm leading-6">{item.observations || 'No observations recorded.'}</p></SectionCard><SectionCard title="Linked violations" subtitle="Issues raised during this inspection"><WorkflowRows rows={item.violations.map((row) => ({ id: row.id, title: row.title, meta: `${row.severity} · ${row.assignedTo} · due ${row.deadline}`, status: row.status }))} empty="No violations linked." /></SectionCard><SectionCard title="Corrective actions" subtitle="Resolution work linked to this inspection"><WorkflowRows rows={item.actions.map((row) => ({ id: row.id, title: row.title, meta: `${row.responsiblePerson} · due ${row.deadline}`, status: row.status }))} empty="No corrective actions linked." /></SectionCard></div> }

function WorkflowForm({ onSubmit, label, children }: { onSubmit: (event: FormEvent) => void; label: string; children: ReactNode }) { return <form onSubmit={onSubmit} className="gap-4 grid sm:grid-cols-2 bg-minsos-50 p-5 border border-minsos-100 rounded-xl">{children}<button className="bg-minsos-600 px-4 py-2.5 rounded-lg w-fit font-semibold text-white text-sm">{label}</button></form> }
function Input({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="font-medium text-slate-700 text-sm">{label}<input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} className="block bg-white mt-1.5 px-3 py-2.5 border border-slate-300 rounded-lg w-full text-sm" /></label> }
function Select({ label, value, onChange, options, required = false }: { label: string; value: string; onChange: (value: string) => void; options: WorkflowLookup[]; required?: boolean }) { return <label className="font-medium text-slate-700 text-sm">{label}<select value={value} required={required} onChange={(event) => onChange(event.target.value)} className="block bg-white mt-1.5 px-3 py-2.5 border border-slate-300 rounded-lg w-full text-sm"><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label ?? option.name}</option>)}</select></label> }
function Heading({ title, description }: { title: string; description: string }) { return <div><p className="font-semibold text-minsos-600 text-sm">Core workflow</p><h2 className="mt-1 font-bold text-slate-900 text-2xl">{title}</h2><p className="mt-1 text-slate-500 text-sm">{description}</p></div> }
function Info({ label, value }: { label: string; value: string }) { return <div className="bg-white p-4 border border-slate-200 rounded-xl"><p className="font-semibold text-slate-500 text-xs uppercase">{label}</p><p className="mt-2 font-semibold text-slate-800 text-sm">{value}</p></div> }
function WorkflowRows({ rows, empty }: { rows: { id: string; title: string; meta: string; status: string }[]; empty: string }) { return rows.length ? <div className="divide-y divide-slate-100">{rows.map((row) => <div key={row.id} className="flex justify-between items-center gap-4 px-5 py-4"><div><p className="font-semibold text-slate-800 text-sm">{row.title} · {row.id}</p><p className="mt-1 text-slate-500 text-xs">{row.meta}</p></div><StatusBadge value={row.status} /></div>)}</div> : <State text={empty} /> }
function State({ text, error = false }: { text: string; error?: boolean }) { return <div className={`px-5 py-8 text-sm ${error ? 'text-red-600' : 'text-slate-500'}`}>{text}</div> }