import { Link, useParams } from 'react-router-dom'
import { SectionCard, StatusBadge } from '../components/ui'
import { workflowActions, workflowInspections, workflowViolations } from '../data/workflowData'

export function InspectionListPage() {
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-minsos-600">Core workflow</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Inspection register</h2><p className="mt-1 text-sm text-slate-500">Field and statutory inspections, including their follow-up work.</p></div><button className="rounded-lg bg-minsos-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-minsos-700">+ New inspection</button></div><SectionCard title="All inspections" subtitle="Select an inspection to view field evidence, observations and linked workflow records."><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Inspection</th><th className="px-4 py-3">Mine</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Inspector</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Workflow</th></tr></thead><tbody className="divide-y divide-slate-100">{workflowInspections.map((inspection) => <tr key={inspection.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><Link to={`../inspections/${inspection.id}`} className="font-semibold text-minsos-600 hover:text-minsos-800">{inspection.id}</Link><p className="mt-0.5 text-xs text-slate-500">{inspection.completedOn ?? `Scheduled ${inspection.scheduledFor}`}</p></td><td className="px-4 py-4"><p className="font-medium text-slate-800">{inspection.mine}</p><p className="text-xs text-slate-500">{inspection.mineCode}</p></td><td className="px-4 py-4 text-slate-600">{inspection.type}</td><td className="px-4 py-4 text-slate-600">{inspection.inspector}</td><td className="px-4 py-4"><StatusBadge value={inspection.status} /></td><td className="px-5 py-4 text-right text-xs text-slate-500">{inspection.violationCount} violation{inspection.violationCount === 1 ? '' : 's'} · {inspection.actionCount} action{inspection.actionCount === 1 ? '' : 's'}</td></tr>)}</tbody></table></div></SectionCard><p className="text-xs text-slate-400">Demo workflow data will be replaced by the inspections API after integration.</p></div>
}

export function InspectionDetailPage() {
  const { id } = useParams(); const inspection = workflowInspections.find((item) => item.id === id)
  if (!inspection) return <div className="rounded-xl border border-slate-200 bg-white p-8"><h2 className="text-xl font-bold text-slate-900">Inspection not found</h2><Link to="../inspections" className="mt-3 inline-block text-sm font-semibold text-minsos-600">Return to inspection register</Link></div>
  const violations = workflowViolations.filter((item) => item.inspectionId === inspection.id); const actions = workflowActions.filter((item) => item.inspectionId === inspection.id)
  return <div className="space-y-6"><div><Link to="../inspections" className="text-sm font-semibold text-minsos-600 hover:text-minsos-800">← Inspection register</Link><div className="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold text-minsos-600">{inspection.mine} · {inspection.mineCode}</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">{inspection.id} — {inspection.type}</h2><p className="mt-1 text-sm text-slate-500">Completed {inspection.completedOn ?? '—'} by {inspection.inspector}</p></div><StatusBadge value={inspection.status} /></div></div><div className="grid gap-4 sm:grid-cols-3"><Info label="Field location" value={inspection.location} /><Info label="GPS capture" value={`${inspection.latitude.toFixed(4)}, ${inspection.longitude.toFixed(4)}`} /><Info label="Evidence photos" value={`${inspection.photoCount} attached`} /></div><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><SectionCard title="Inspector observations" subtitle="Recorded during the field visit"><div className="px-5 py-5"><p className="text-sm leading-6 text-slate-700">{inspection.observations}</p><div className="mt-5 flex flex-wrap gap-2">{Array.from({ length: inspection.photoCount }, (_, index) => <span key={index} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-600">Photo {index + 1} · evidence metadata</span>)}{inspection.photoCount === 0 && <p className="text-sm text-slate-500">No photos attached yet.</p>}</div></div></SectionCard><SectionCard title="Location metadata" subtitle="Captured with the inspection record"><div className="px-5 py-5"><div className="rounded-lg border border-dashed border-minsos-200 bg-minsos-50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-minsos-700">GPS coordinate</p><p className="mt-2 font-mono text-sm text-slate-700">{inspection.latitude}, {inspection.longitude}</p><p className="mt-3 text-xs leading-5 text-slate-500">The backend should store coordinates, accuracy and capture time; the web app can render a map once a GIS provider is chosen.</p></div></div></SectionCard></div><SectionCard title="Violations raised" subtitle="Each violation is traceable to this inspection"><WorkflowTable rows={violations.map((item) => ({ id: item.id, title: item.title, meta: `${item.severity} severity · assigned to ${item.assignedTo}`, status: item.status }))} empty="No violations were raised in this inspection." /></SectionCard><SectionCard title="Corrective actions" subtitle="Actions created to resolve the recorded violations"><WorkflowTable rows={actions.map((item) => ({ id: item.id, title: item.title, meta: `${item.responsiblePerson} · due ${item.deadline} · ${item.evidenceCount} evidence item${item.evidenceCount === 1 ? '' : 's'}`, status: item.status }))} empty="No corrective actions are linked to this inspection." /></SectionCard></div>
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-slate-800">{value}</p></div> }
function WorkflowTable({ rows, empty }: { rows: { id: string; title: string; meta: string; status: string }[]; empty: string }) { return rows.length ? <div className="divide-y divide-slate-100">{rows.map((row) => <div key={row.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-semibold text-slate-800">{row.title} <span className="font-normal text-slate-400">· {row.id}</span></p><p className="mt-1 text-xs text-slate-500">{row.meta}</p></div><StatusBadge value={row.status} /></div>)}</div> : <div className="px-5 py-8 text-sm text-slate-500">{empty}</div> }
