import { useState } from 'react'
import { SectionCard, StatusBadge } from '../components/ui'
import { workflowActions, workflowViolations } from '../data/workflowData'
import type { ActionStatus, WorkflowAction } from '../types'

export function ViolationsPage() {
  const [violations, setViolations] = useState(workflowViolations)
  const updateStatus = (id: string) => setViolations((current) => current.map((item) => item.id === id ? { ...item, status: item.status === 'Open' ? 'Under review' : 'Resolved' } : item))
  return <div className="space-y-6"><PageIntro label="Core workflow" title="Violation register" description="Review severity, ownership, evidence and resolution progress for every recorded violation." action="+ Record violation" /><SectionCard title="Open and resolved violations" subtitle="Use the review action to move a violation through its resolution workflow."><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Violation</th><th className="px-4 py-3">Mine / inspection</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Owner / deadline</th><th className="px-4 py-3">Evidence</th><th className="px-5 py-3 text-right">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{violations.map((item) => <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.title}</p><p className="mt-0.5 text-xs text-slate-500">{item.id} · {item.category}</p></td><td className="px-4 py-4"><p className="text-slate-700">{item.mine}</p><p className="text-xs text-slate-500">{item.inspectionId}</p></td><td className="px-4 py-4"><StatusBadge value={item.severity} /></td><td className="px-4 py-4"><p className="text-slate-700">{item.assignedTo}</p><p className="text-xs text-slate-500">Due {item.deadline}</p></td><td className="px-4 py-4 text-slate-600">{item.evidenceCount} item{item.evidenceCount === 1 ? '' : 's'}</td><td className="px-5 py-4 text-right"><button onClick={() => updateStatus(item.id)} className="mr-3 text-xs font-semibold text-minsos-600 hover:text-minsos-800">{item.status === 'Resolved' ? 'Resolved' : 'Update'}</button><StatusBadge value={item.status} /></td></tr>)}</tbody></table></div></SectionCard><PrototypeNote /></div>
}

export function ActionsPage() {
  const [actions, setActions] = useState(workflowActions)
  const verify = (id: string) => setActions((current) => current.map((item) => item.id === id ? { ...item, status: 'Verified' as ActionStatus, verificationNote: 'Verified by manager in prototype' } : item))
  const advance = (id: string) => setActions((current) => current.map((item) => item.id === id ? { ...item, status: item.status === 'Open' || item.status === 'Overdue' ? 'In progress' : 'Completed' } : item))
  return <div className="space-y-6"><PageIntro label="Core workflow" title="Corrective action tracker" description="Assign actions, monitor deadlines, inspect evidence and verify closure." action="+ Create action" /><SectionCard title="Corrective actions" subtitle="The verification control is enabled only after an action is complete in the API-backed version."><div className="divide-y divide-slate-100">{actions.map((item) => <ActionRow key={item.id} action={item} onAdvance={() => advance(item.id)} onVerify={() => verify(item.id)} />)}</div></SectionCard><PrototypeNote /></div>
}

function ActionRow({ action, onAdvance, onVerify }: { action: WorkflowAction; onAdvance: () => void; onVerify: () => void }) { const canVerify = action.status === 'Completed'; return <div className="flex flex-col gap-3 px-5 py-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold text-slate-800">{action.title} <span className="font-normal text-slate-400">· {action.id}</span></p><p className="mt-1 text-xs text-slate-500">{action.mine} · {action.responsiblePerson} · due {action.deadline} · {action.evidenceCount} evidence item{action.evidenceCount === 1 ? '' : 's'}</p>{action.verificationNote && <p className="mt-1 text-xs font-medium text-emerald-700">{action.verificationNote}</p>}</div><div className="flex items-center gap-3"><StatusBadge value={action.status} />{action.status !== 'Verified' && <button onClick={onAdvance} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Update status</button>}{canVerify && <button onClick={onVerify} className="rounded-lg bg-minsos-600 px-3 py-2 text-xs font-semibold text-white hover:bg-minsos-700">Verify action</button>}</div></div> }
function PageIntro({ label, title, description, action }: { label: string; title: string; description: string; action: string }) { return <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-minsos-600">{label}</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><button className="rounded-lg bg-minsos-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-minsos-700">{action}</button></div> }
function PrototypeNote() { return <p className="text-xs text-slate-400">Status controls demonstrate the intended workflow locally. API requests and persistence will be enabled after the backend contract in backend.md is implemented.</p> }
